// ignore_for_file: file_names, unnecessary_this, prefer_const_constructors, use_key_in_widget_constructors, no_logic_in_create_state, prefer_is_empty,  unnecessary_string_interpolations,  unnecessary_overrides, avoid_print, prefer_typing_uninitialized_variables, prefer_final_fields, sized_box_for_whitespace, deprecated_member_use, prefer_void_to_null, avoid_returning_null_for_void, constant_identifier_names, avoid_function_literals_in_foreach_calls, avoid_unnecessary_containers, prefer_adjacent_string_concatenation, prefer_if_null_operators, prefer_null_aware_operators
class SystemFlagNameList {
  late String gst;
  late String razorPayKeyId;
  late String razorPayKeySecret;
  late String astrologyApiUserId;
  late String astrologyApiKey;
  late String rapidApiKey;
  late String rapidApiHost;
  late String agoraAppId;
  late String agoraAppCertificate;
  late String agoraKey;
  late String agoraSecret;
  late String googleAccessKey;
  late String googleSecretKey;
  late String googleBucketName;
  late String stripeSecret;
  late String paymentMode;
  late String apple;
  late String website;
  late String youtube;
  late String instra;
  late String facebook;
  late String linkedin;
  late String pintrest;
  late String dailyHoroscope;
  late String freeKundli;
  late String kundliMatching;
  late String astromall;
  late String todayPanchang;
  late String appName;
  late String currency;
  late String behindScenes;

  SystemFlagNameList() {
    gst = 'Gst';
    razorPayKeyId = 'RazorPayKeyId';
    razorPayKeySecret = 'RazorPayKeySecret';
    astrologyApiUserId = 'AstrologyApiUserId';
    astrologyApiKey = 'AstrologyApiKey';
    rapidApiKey = 'RapidApiKey';
    rapidApiHost = 'RapidApiHost';
    agoraAppId = 'AgoraAppId';
    agoraAppCertificate = 'AgoraAppCertificate';
    agoraKey = 'AgoraKey';
    agoraSecret = 'AgoraSecret';
    googleAccessKey = 'GoogleAccessKey';
    googleSecretKey = 'GoogleSecretKey';
    googleBucketName = 'GoogleBucketName';
    stripeSecret = 'StripeSecret';
    paymentMode = 'PaymentMode';
    apple = 'Apple';
    website = 'Website';
    youtube = 'Youtube';
    facebook = 'Facebook';
    instra = 'Instagram';
    linkedin = 'LinkedIn';
    pintrest = 'Pintrest';
    dailyHoroscope = 'DailyHoroscope';
    freeKundli = 'FreeKundali';
    kundliMatching = 'KundaliMatching';
    astromall = 'Astromall';
    todayPanchang = 'TodayPanchang';
    appName = 'AppName';
    currency = 'Currency';
    behindScenes = 'BehindScenes';
  }
}
