import 'package:AstroGuru/controllers/advancedPanchangController.dart';
import 'package:AstroGuru/controllers/astrologer_assistant_controller.dart';
import 'package:AstroGuru/controllers/astrologyBlogController.dart';
import 'package:AstroGuru/controllers/astromallController.dart';
import 'package:AstroGuru/controllers/callController.dart';
import 'package:AstroGuru/controllers/IntakeController.dart';
import 'package:AstroGuru/controllers/chatController.dart';
import 'package:AstroGuru/controllers/customer_support_controller.dart';
import 'package:AstroGuru/controllers/dailyHoroscopeController.dart';
import 'package:AstroGuru/controllers/dropDownController.dart';
import 'package:AstroGuru/controllers/filtterTabController.dart';
import 'package:AstroGuru/controllers/follow_astrologer_controller.dart';
import 'package:AstroGuru/controllers/freeServiceController.dart';
import 'package:AstroGuru/controllers/gift_controller.dart';
import 'package:AstroGuru/controllers/history_controller.dart';
import 'package:AstroGuru/controllers/homeController.dart';
import 'package:AstroGuru/controllers/imageController.dart';
import 'package:AstroGuru/controllers/kundliController.dart';
import 'package:AstroGuru/controllers/kundliMatchingController.dart';
import 'package:AstroGuru/controllers/languageController.dart';
import 'package:AstroGuru/controllers/life_cycle_controller.dart';
import 'package:AstroGuru/controllers/liveAstrologerController.dart';
import 'package:AstroGuru/controllers/loginController.dart';
import 'package:AstroGuru/controllers/networkController.dart';
import 'package:AstroGuru/controllers/razorPayController.dart';
import 'package:AstroGuru/controllers/reportController.dart';
import 'package:AstroGuru/controllers/reportTabFiltter.dart';
import 'package:AstroGuru/controllers/reviewController.dart';
import 'package:AstroGuru/controllers/search_controller.dart';
import 'package:AstroGuru/controllers/search_place_controller.dart';
import 'package:AstroGuru/controllers/settings_controller.dart';
import 'package:AstroGuru/controllers/skillController.dart';
import 'package:AstroGuru/controllers/splashController.dart';
import 'package:AstroGuru/controllers/themeController.dart';
import 'package:AstroGuru/controllers/timer_controller.dart';
import 'package:AstroGuru/controllers/upcoming_controller.dart';
import 'package:AstroGuru/controllers/userProfileController.dart';
import 'package:AstroGuru/controllers/walletController.dart';
import 'package:get/get.dart';
import 'package:AstroGuru/controllers/bottomNavigationController.dart';

import '../../controllers/counsellorController.dart';
import '../../controllers/liveController.dart';

class NetworkBinding extends Bindings {
  @override
  void dependencies() {
    Get.put(BottomNavigationController());
    Get.put(LiveController());
    Get.lazyPut<SplashController>(() => SplashController(), fenix: true);
    Get.lazyPut<LoginController>(() => LoginController(), fenix: true);
    Get.lazyPut<ChatController>(() => ChatController(), fenix: true);
    Get.lazyPut<CallController>(() => CallController(), fenix: true);
    Get.lazyPut<UserProfileController>(() => UserProfileController(), fenix: true);
    Get.lazyPut<ReportController>(() => ReportController(), fenix: true);
    Get.lazyPut<DropDownController>(() => DropDownController(), fenix: true);
    Get.lazyPut<AstromallController>(() => AstromallController(), fenix: true);
    Get.lazyPut<WalletController>(() => WalletController(), fenix: true);
    Get.lazyPut<DailyHoroscopeController>(() => DailyHoroscopeController(), fenix: true);
    Get.lazyPut<KundliController>(() => KundliController(), fenix: true);
    Get.lazyPut<HomeController>(() => HomeController(), fenix: true);
    Get.lazyPut<FreeServiceController>(() => FreeServiceController(), fenix: true);
    Get.lazyPut<KundliMatchingController>(() => KundliMatchingController(), fenix: true);
    Get.lazyPut<CounsellorController>(() => CounsellorController(), fenix: true);
    Get.lazyPut<NetworkController>(() => NetworkController(), fenix: true);
    Get.lazyPut<GiftController>(() => GiftController(), fenix: true);
    Get.lazyPut<SearchPlaceController>(() => SearchPlaceController(), fenix: true);
    Get.lazyPut<ImageControlller>(() => ImageControlller(), fenix: true);
    Get.lazyPut<SettingsController>(() => SettingsController(), fenix: true);
    Get.lazyPut<FollowAstrologerController>(() => FollowAstrologerController(), fenix: true);
    Get.lazyPut<ReviewController>(() => ReviewController(), fenix: true);
    Get.lazyPut<SkillController>(() => SkillController(), fenix: true);
    Get.lazyPut<LanguageController>(() => LanguageController(), fenix: true);
    Get.lazyPut<HomeCheckController>(() => HomeCheckController(), fenix: true);
    Get.lazyPut<FiltterTabController>(() => FiltterTabController(), fenix: true);
    Get.lazyPut<TimerController>(() => TimerController(), fenix: true);
    Get.lazyPut<LiveAstrologerController>(() => LiveAstrologerController(), fenix: true);
    Get.lazyPut<RazorPayController>(() => RazorPayController(), fenix: true);
    Get.lazyPut<PanchangController>(() => PanchangController(), fenix: true);
    Get.lazyPut<IntakeController>(() => IntakeController(), fenix: true);
    Get.lazyPut<ReportFilterTabController>(() => ReportFilterTabController(), fenix: true);
    Get.lazyPut<SearchController>(() => SearchController(), fenix: true);
    Get.lazyPut<HistoryController>(() => HistoryController(), fenix: true);
    Get.lazyPut<BlogController>(() => BlogController(), fenix: true);
    Get.lazyPut<CustomerSupportController>(() => CustomerSupportController(), fenix: true);
    Get.lazyPut<AstrologerAssistantController>(() => AstrologerAssistantController(), fenix: true);
    Get.lazyPut<UpcomingController>(() => UpcomingController(), fenix: true);
    Get.lazyPut<ThemeController>(() => ThemeController(), fenix: true);
  }
}
